socks5_proxy = "socks5://127.0.0.1:56509"

dhcp = true
listeners = []

[flags]
no_tun = true
use_smoltcp = true
enable_quic_proxy = true

[[acl.acl_v1.chains]]
name = "block_all_inbound"
chain_type = 1
description = ""
enabled = true
rules = []
default_action = 2

[network_identity]
network_name = "e0ce884a-6dc4-4615-baf4-fbf233686b1e"